version: '3.9'
services:
  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor:latest
    ports:
      - '8080:8080'
  swagger-ui:
    container_name: swagger-ui
    environment:
      SWAGGER_JSON: /openapi.yaml
    image: swaggerapi/swagger-ui:latest
    ports:
      - '8081:8080'
    volumes:
      - ./openapi.yaml:/openapi.yaml
